name: Build & Upload
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ENVS:
        required: false

jobs:
  build-apk:
    name: APK Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3.1.0

      - name: Update Env for custom build
        run: |
          echo "${{ secrets.ENVS }}" >> .env

      - name: Build Revanced APKs
        run: |
          docker-compose up

      - name: Upload Build APKS
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Built-APKs
          path: |
            apks/*-output.apk
            apks/VancedMicroG.apk"
          if-no-files-found: error
