name: GitHub Cleanup

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  release-cleanup:
    name: GitHub Cleanup
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Delete Older Releases
        uses: nikhilbadyal/ghaction-rm-releases@v0.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RELEASE_PATTERN: '[\s\S]*'
  workflow-cleanup:
    uses: nikhilbadyal/ghactions/.github/workflows/github-workflow-cleaner.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
