name: VirusTotal Scan

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      VT_API_KEY:
        required: true
      GH_TOKEN:
        required: true

jobs:
  virustotal:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: VirusTotal Scan
        if: ${{ env.HAVE_VT_API_KEY == 'true' }}
        uses: nikhilbadyal/ghaction-virustotal@master
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          request_rate: 4
          files: |
            .apk$
env:
  HAVE_VT_API_KEY: ${{ secrets.VT_API_KEY != '' }}
